### PR TITLE
feat: extend export with protected nodes defined by user.

### PR DESCRIPTION
**Pull request by ronoaldo**

### CODE REVIEW

**Comment by ronoaldo** [comment]
References #185 and #184

**Comment by ronoaldo** [comment]
Ready to review / merge! I have tested this on my own server, and the exported regions with --export-all reflect what would be left when you run --prune_unprotected. It was fully working on a 80G map with 125.000.000+ mapblocks, exporting a 4G working sqlite map. This actually provides a nice and safe way to clean the map as the resulting and smaller version can be checked before it goes live.

**Review by BuckarooBanzay — APPROVED** [review]
lgtm, nice work :+1:

i have to test this on the pandorabox backup soon(-ish) i wonder how much space we could save :thinking:

**Comment by ronoaldo** [comment]
Nice! Yeah, on my case, there are huge builds. Like an enormous tunnel with 18km of distance (in game distance), a _giga_ factory with automations galore and several player bases around the world. However, the majority of places were just mapgen stuff with no protected regions so the reduced size was significant.

**Review by BuckarooBanzay — APPROVED** [review]
lgtm :+1:

**Pull request merged**
